// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt8YuY3ch26RN8JCJ0ViOBwMGvzSr97Bo',
    appId: '1:1034965519981:web:e839f70fabe11623877964',
    messagingSenderId: '1034965519981',
    projectId: 'thecoffeeandcode-36c1f',
    authDomain: 'thecoffeeandcode-36c1f.firebaseapp.com',
    storageBucket: 'thecoffeeandcode-36c1f.appspot.com',
    measurementId: 'G-BTY309PZTC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkGluvNZ1qM01AxJiYa9K_46_br4846SM',
    appId: '1:1034965519981:android:dc30dc1090c820b3877964',
    messagingSenderId: '1034965519981',
    projectId: 'thecoffeeandcode-36c1f',
    storageBucket: 'thecoffeeandcode-36c1f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfp3GeGtfBhWeCSWpkhoUb08CpBZct59g',
    appId: '1:1034965519981:ios:dfc2a77c623e1a47877964',
    messagingSenderId: '1034965519981',
    projectId: 'thecoffeeandcode-36c1f',
    storageBucket: 'thecoffeeandcode-36c1f.appspot.com',
    iosClientId: '1034965519981-j2g0hluo725f48lviq880cpcpg8s6sur.apps.googleusercontent.com',
    iosBundleId: 'com.example.coffee',
  );
}
